name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Contribution SVG
        uses: Platane/snk@v3
        with:
          github_user_name: sumansingh20
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          mkdir -p dist

          git add dist/snake.svg dist/snake-dark.svg

          git commit -m "Updated Snake Contribution Graph" || echo "No changes to commit"

          git push https://sumansingh20:${{ secrets.PAT_TOKEN }}@github.com/sumansingh20/sumansingh20.git
