name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create output folder
        run: mkdir -p output

      - name: Generate Pacman Graph
        uses: MauroDesouza/github-activity-readme@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GRAPH_TYPE: pacman
          OUTPUT_PATH: ./output/pacman-contribution-graph.svg
          COMMIT_MESSAGE: "Update Pacman Contribution Graph"

      - name: Push changes with PAT
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/pacman-contribution-graph.svg
          git commit -m "Update Pacman Contribution Graph" || echo "No changes"
          git push https://sumansingh20:${{ secrets.PAT_TOKEN }}@github.com/sumansingh20/sumansingh20.git
