name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman graph
        uses: maurodesouza/pacman-contribution-graph@main
        with:
          user: sumansingh20
          color_scheme: "github"
          output_dir: "output"

      - name: Push Pacman graph to output branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git add output/pacman-contribution-graph.svg || true
          git commit -m "Update Pacman graph" || true
          git push https://sumansingh20:${{ secrets.PAT_TOKEN }}@github.com/sumansingh20/sumansingh20.git HEAD:output
