name: Generate Profile Assets

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: write

    steps:
      - name: Generate snake contribution SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sumansingh20
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Generate pacman contribution SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: sumansingh20
          games: "pacman"
          hide_month_labels: "false"

      - name: Publish SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
